// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://gvpsfgzstiqbjlgqglyh.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Imd2cHNmZ3pzdGlxYmpsZ3FnbHloIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NjA3NjQ4NjEsImV4cCI6MjA3NjM0MDg2MX0._-3-RCHJ1eXo_A1tbo6bgM-akZgnY74SxtWbz3gbJDM";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});